### ISSUE TITLE
Set up a network of Hyperledger Indy nodes

### ISSUE THREAD

**Issue by i1uxaermakov** [DZhangLab/HIDe-infrastructure#2]

**Comment by i1uxaermakov** [comment]
- See if it is feasible and how much does it cost (if it does). 
- Continue reading the SSI book to get a general understanding of the infrastructure and the interaction between the components.

**Comment by ebenissan** [comment]
- [ ] Documentation and notes on findings

**Comment by ebenissan** [comment]
No longer pursuing Indy
