### ISSUE TITLE
How to configure the number of nodes we must instantiate, what configurations need to be done

### ISSUE THREAD

**Issue by ebenissan** [DZhangLab/HIDe-infrastructure#3]
- [x] Creating a channel
- [x] Adding org to the channel
- [x] How to onboard various numbers of nodes on the network
- [ ] Customized chaincode
- [x] Configuring the network

**Comment by AbirMazumder99** [comment]
1. I modified all required scripts to instantiate a network with 3 orgs (1 peer each) instead of 2. 
2. ./network.sh up command is successful
3. ./network.sh createChannel is unsuccessful. The join channel command (peer channel join -b $BLOCKFILE >&log.txt) fails for the 3rd organization. Not sure what to do from here on.

**Comment by katherinehuu** [comment]
Hyperledger Compose: chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/viewer.html?pdfurl=https%3A%2F%2Fwww.redbooks.ibm.com%2Fredpapers%2Fpdfs%2Fredp5492.pdf&clen=3437278&chunk=true

**Comment by Pei-Shan-Tan** [comment]
Create a channel and Adding an org to the channel documentation added
https://github.com/DZhangLab/HIDe-infrastructure/blob/main/README.md

**Comment by AbirMazumder99** [comment]
- Found this fabric network generator that generates a custom based on a .json file that we can define ourselves (https://github.com/suddutt1/fabricnetgenerator)
- inspected the repo to see if it is compatible with Hypderledger 2.x.
- Debugged certain errors to make it work with Fabric 2.2 (which is very similar to the latest version so we should be good
- updated Infrastructure repo with a new branch with a customized consortium
- Currently it only supports Go Smart Contracts. Need to configure to work with JS Smart Contracts
- This might just be the best breakthrough for our Infrastructure Customization so far!!!
